name: Test GitHub Secrets

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print Repository Owner
        run: echo "Repository Owner = ${{github.repository_owner}}""

      - name: Print Docker Username Secret
        run: echo "Docker Username = ${{github.DOCKER_USERNAME}}"
